# Generated by Django 4.1.5 on 2023-05-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectArea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('uri', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('country', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarlyOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationsInTopJournalPercentiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='PatentCitedScholarlyOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='PatentCitationsPerScholarlyOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='PatentCitationsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='OutputsInTopCitationPercentiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='Hindices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='FieldWeightedCitationImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='CitingPatentsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='CitationsPerPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
        migrations.CreateModel(
            name='CitationCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('value', models.FloatField()),
                ('subjectAreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.university')),
            ],
        ),
    ]
