# Generated by Django 4.1.9 on 2023-05-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubjectArea",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Id głównej dziedziny naukowej. Id opowiada Id z Scival-a",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa głównej dziedziny naukowej",
                        max_length=150,
                        unique=True,
                        verbose_name="Dziedzina Naukowa",
                    ),
                ),
                (
                    "uri",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Uri głównej dziedziny naukowej. Uri jest parametrem filtrującym zapytanie z Scival-a",
                        max_length=150,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dziedzina naukowa",
                "verbose_name_plural": "Dziedziny naukowe",
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="Id uczelni. Id opowiada Id z Scival-a",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nazwa uczelni",
                        max_length=150,
                        unique=True,
                        verbose_name="Uczelnia",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Polska",
                        help_text="Kraj w którym znajduje się dana uczelnia",
                        max_length=150,
                        verbose_name="Kraj",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uczelnia",
                "verbose_name_plural": "Uczelnie",
            },
        ),
        migrations.CreateModel(
            name="ScholarlyOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka ScholaryOutput",
                "verbose_name_plural": "Metryki ScholaryOutput",
            },
        ),
        migrations.CreateModel(
            name="PublicationsInTopJournalPercentiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka PublicationsInTopJournalPercentiles",
                "verbose_name_plural": "Metryki PublicationsInTopJournalPercentiles",
            },
        ),
        migrations.CreateModel(
            name="PatentCitedScholarlyOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka PatentCitedScholarlyOutput",
                "verbose_name_plural": "Metryki PatentCitedScholarlyOutput",
            },
        ),
        migrations.CreateModel(
            name="PatentCitationsPerScholarlyOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka PatentCitationsPerScholarlyOutput",
                "verbose_name_plural": "Metryki PatentCitationsPerScholarlyOutput",
            },
        ),
        migrations.CreateModel(
            name="PatentCitationsCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka PatentCitationsCount",
                "verbose_name_plural": "Metryki PatentCitationsCount",
            },
        ),
        migrations.CreateModel(
            name="OutputsInTopCitationPercentiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka OutputsInTopCitationPercentiles",
                "verbose_name_plural": "Metryki OutputsInTopCitationPercentiles",
            },
        ),
        migrations.CreateModel(
            name="Hindices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka Hindices",
                "verbose_name_plural": "Metryki Hindices",
            },
        ),
        migrations.CreateModel(
            name="FieldWeightedCitationImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka FieldWeightedCitationImpact",
                "verbose_name_plural": "Metryki FieldWeightedCitationImpact",
            },
        ),
        migrations.CreateModel(
            name="CollaborationImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka CollaborationImpact",
                "verbose_name_plural": "Metryki CollaborationImpact",
            },
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka Collaboration",
                "verbose_name_plural": "Metryki Collaboration",
            },
        ),
        migrations.CreateModel(
            name="CitingPatentsCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka CitingPatentsCount",
                "verbose_name_plural": "Metryki CitingPatentsCount",
            },
        ),
        migrations.CreateModel(
            name="CitationsPerPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka CitationsPerPublication",
                "verbose_name_plural": "Metryki CitationsPerPublication",
            },
        ),
        migrations.CreateModel(
            name="CitationCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10)),
                ("value", models.FloatField()),
                (
                    "subjectAreaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.subjectarea",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metryka CitationCount",
                "verbose_name_plural": "Metryki CitationCount",
            },
        ),
    ]
