# Generated by Django 4.1.9 on 2023-05-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_wartosciMogaBycNone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hindices",
            name="subjectAreaId",
        ),
        migrations.RemoveField(
            model_name="hindices",
            name="universityId",
        ),
        migrations.RemoveField(
            model_name="patentcitationscount",
            name="subjectAreaId",
        ),
        migrations.RemoveField(
            model_name="patentcitationscount",
            name="universityId",
        ),
        migrations.RemoveField(
            model_name="patentcitationsperscholarlyoutput",
            name="subjectAreaId",
        ),
        migrations.RemoveField(
            model_name="patentcitationsperscholarlyoutput",
            name="universityId",
        ),
        migrations.RemoveField(
            model_name="patentcitedscholarlyoutput",
            name="subjectAreaId",
        ),
        migrations.RemoveField(
            model_name="patentcitedscholarlyoutput",
            name="universityId",
        ),
        migrations.DeleteModel(
            name="CitingPatentsCount",
        ),
        migrations.DeleteModel(
            name="Hindices",
        ),
        migrations.DeleteModel(
            name="PatentCitationsCount",
        ),
        migrations.DeleteModel(
            name="PatentCitationsPerScholarlyOutput",
        ),
        migrations.DeleteModel(
            name="PatentCitedScholarlyOutput",
        ),
    ]
