# Generated by Django 4.1.5 on 2023-05-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_usuniecieNiepotrzebnychModeli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa wydziału', max_length=150, verbose_name='Wydział')),
                ('subjectAreas', models.ManyToManyField(to='mainApp.subjectarea')),
                ('universityId', models.ForeignKey(help_text='Id uczelni. Id opowiada Id z Scival-a', on_delete=django.db.models.deletion.CASCADE, to='mainApp.university', verbose_name='Id Uczelni')),
            ],
            options={
                'verbose_name': 'Wydział',
                'verbose_name_plural': 'Wydziały',
            },
        ),
    ]
