# Generated by Django 4.1.5 on 2023-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_usuniecieNiepotrzebnychModeli'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationsCountPerYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicationsCount', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ('year',),
            },
        ),
    ]
