# Generated by Django 4.1.9 on 2023-06-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_usuniecieNiepotrzebnychModeli"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citationcount",
            options={
                "verbose_name": "Liczba cytowan",
                "verbose_name_plural": "Liczba cytowan",
            },
        ),
        migrations.AlterModelOptions(
            name="citationsperpublication",
            options={
                "verbose_name": "Liczba cytowan na publikacje",
                "verbose_name_plural": "Liczba cytowan na publikacje",
            },
        ),
        migrations.AlterModelOptions(
            name="collaboration",
            options={
                "verbose_name": "Kolaboracje",
                "verbose_name_plural": "Kolaboracje",
            },
        ),
        migrations.AlterModelOptions(
            name="collaborationimpact",
            options={
                "verbose_name": "Impakt kolaboracji",
                "verbose_name_plural": "Impakt kolaboracji",
            },
        ),
        migrations.AlterModelOptions(
            name="fieldweightedcitationimpact",
            options={
                "verbose_name": "Waga impaktu cytowan",
                "verbose_name_plural": "Waga impaktu cytowan",
            },
        ),
        migrations.AlterModelOptions(
            name="outputsintopcitationpercentiles",
            options={
                "verbose_name": "Wyniki w najwyższych percentylach cytowań",
                "verbose_name_plural": "Wyniki w najwyższych percentylach cytowań",
            },
        ),
        migrations.AlterModelOptions(
            name="publicationsintopjournalpercentiles",
            options={
                "verbose_name": "Procent publikacji w topowych dziennikach",
                "verbose_name_plural": "Procent publikacji w topowych dziennikach",
            },
        ),
        migrations.AlterModelOptions(
            name="scholarlyoutput",
            options={
                "verbose_name": "Wyniki naukowe",
                "verbose_name_plural": "Wyniki naukowe",
            },
        ),
        migrations.RemoveField(
            model_name="collaboration",
            name="value",
        ),
        migrations.RemoveField(
            model_name="collaborationimpact",
            name="value",
        ),
        migrations.AddField(
            model_name="collaboration",
            name="InstitutionalPercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość calkowita kolaboracji",
                null=True,
                verbose_name="Procentowa wartość calkowita",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="InstitutionalValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość calkowita kolaboracji",
                null=True,
                verbose_name="Wartość calkowita",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="InternationalPercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość miedzynarodowa kolaboracji",
                null=True,
                verbose_name="Procentowa wartość miedzynarodowa",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="InternationalValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość miedzynarodowa kolaboracji",
                null=True,
                verbose_name="Wartość miedzynarodowa",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="NationalPercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość narodowa kolaboracji",
                null=True,
                verbose_name="Procentowa wartość narodowa",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="NationalValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość narodowa kolaboracji",
                null=True,
                verbose_name="Wartość narodowa",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="SingleAuthorshipPercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość pojedynczego autorstwa kolaboracji",
                null=True,
                verbose_name="Procentowa wartość pojedynczego autorstwa",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="SingleAuthorshipValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość pojedynczego autorstwa kolaboracji",
                null=True,
                verbose_name="Wartość pojedynczego autorstwa",
            ),
        ),
        migrations.AddField(
            model_name="collaborationimpact",
            name="InstitutionalValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość calkowita impaktu kolaboracji",
                null=True,
                verbose_name="Wartość calkowita",
            ),
        ),
        migrations.AddField(
            model_name="collaborationimpact",
            name="InternationalValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość miedzynarodowa impaktu kolaboracji",
                null=True,
                verbose_name="Wartość miedzynarodowa",
            ),
        ),
        migrations.AddField(
            model_name="collaborationimpact",
            name="NationalValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość narodowa impaktu kolaboracji",
                null=True,
                verbose_name="Wartość narodowa",
            ),
        ),
        migrations.AddField(
            model_name="collaborationimpact",
            name="SingleAuthorshipValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość pojedynczego autorstwa impaktu kolaboracji",
                null=True,
                verbose_name="Wartość pojedynczego autorstwa",
            ),
        ),
    ]
