# Generated by Django 4.1.9 on 2023-06-04 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_alter_citationcount_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outputsintopcitationpercentiles",
            name="value",
        ),
        migrations.RemoveField(
            model_name="publicationsintopjournalpercentiles",
            name="value",
        ),
        migrations.AddField(
            model_name="outputsintopcitationpercentiles",
            name="threshold10PercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość threshold10",
                null=True,
                verbose_name="Procentowa wartość threshold10",
            ),
        ),
        migrations.AddField(
            model_name="outputsintopcitationpercentiles",
            name="threshold10value",
            field=models.FloatField(
                blank=True,
                help_text="Wartość threshold10",
                null=True,
                verbose_name="Wartość threshold10",
            ),
        ),
        migrations.AddField(
            model_name="outputsintopcitationpercentiles",
            name="threshold1PercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość threshold1",
                null=True,
                verbose_name="Procentowa wartość threshold1",
            ),
        ),
        migrations.AddField(
            model_name="outputsintopcitationpercentiles",
            name="threshold1value",
            field=models.FloatField(
                blank=True,
                help_text="Wartość threshold1",
                null=True,
                verbose_name="Wartość threshold1",
            ),
        ),
        migrations.AddField(
            model_name="outputsintopcitationpercentiles",
            name="threshold25PercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość threshold25",
                null=True,
                verbose_name="Procentowa wartość threshold25",
            ),
        ),
        migrations.AddField(
            model_name="outputsintopcitationpercentiles",
            name="threshold25value",
            field=models.FloatField(
                blank=True,
                help_text="Wartość threshold25",
                null=True,
                verbose_name="Wartość threshold25",
            ),
        ),
        migrations.AddField(
            model_name="outputsintopcitationpercentiles",
            name="threshold5PercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość threshold5",
                null=True,
                verbose_name="Procentowa wartość threshold5",
            ),
        ),
        migrations.AddField(
            model_name="outputsintopcitationpercentiles",
            name="threshold5value",
            field=models.FloatField(
                blank=True,
                help_text="Wartość threshold5",
                null=True,
                verbose_name="Wartość threshold5",
            ),
        ),
        migrations.AddField(
            model_name="publicationsintopjournalpercentiles",
            name="threshold10PercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość threshold10",
                null=True,
                verbose_name="Procentowa wartość threshold10",
            ),
        ),
        migrations.AddField(
            model_name="publicationsintopjournalpercentiles",
            name="threshold10value",
            field=models.FloatField(
                blank=True,
                help_text="Wartość threshold10",
                null=True,
                verbose_name="Wartość threshold10",
            ),
        ),
        migrations.AddField(
            model_name="publicationsintopjournalpercentiles",
            name="threshold1PercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość threshold1",
                null=True,
                verbose_name="Procentowa wartość threshold1",
            ),
        ),
        migrations.AddField(
            model_name="publicationsintopjournalpercentiles",
            name="threshold1value",
            field=models.FloatField(
                blank=True,
                help_text="Wartość threshold1",
                null=True,
                verbose_name="Wartość threshold1",
            ),
        ),
        migrations.AddField(
            model_name="publicationsintopjournalpercentiles",
            name="threshold25PercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość threshold25",
                null=True,
                verbose_name="Procentowa wartość threshold25",
            ),
        ),
        migrations.AddField(
            model_name="publicationsintopjournalpercentiles",
            name="threshold25value",
            field=models.FloatField(
                blank=True,
                help_text="Wartość threshold25",
                null=True,
                verbose_name="Wartość threshold25",
            ),
        ),
        migrations.AddField(
            model_name="publicationsintopjournalpercentiles",
            name="threshold5PercentageValue",
            field=models.FloatField(
                blank=True,
                help_text="Procentowa wartość threshold5",
                null=True,
                verbose_name="Procentowa wartość threshold5",
            ),
        ),
        migrations.AddField(
            model_name="publicationsintopjournalpercentiles",
            name="threshold5value",
            field=models.FloatField(
                blank=True,
                help_text="Wartość threshold5",
                null=True,
                verbose_name="Wartość threshold5",
            ),
        ),
    ]
