# Generated by Django 4.1.9 on 2023-06-04 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0005_remove_outputsintopcitationpercentiles_value_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="outputsintopcitationpercentiles",
            old_name="threshold10value",
            new_name="threshold10Value",
        ),
        migrations.RenameField(
            model_name="outputsintopcitationpercentiles",
            old_name="threshold1value",
            new_name="threshold1Value",
        ),
        migrations.RenameField(
            model_name="outputsintopcitationpercentiles",
            old_name="threshold25value",
            new_name="threshold25Value",
        ),
        migrations.RenameField(
            model_name="outputsintopcitationpercentiles",
            old_name="threshold5value",
            new_name="threshold5Value",
        ),
        migrations.RenameField(
            model_name="publicationsintopjournalpercentiles",
            old_name="threshold10value",
            new_name="threshold10Value",
        ),
        migrations.RenameField(
            model_name="publicationsintopjournalpercentiles",
            old_name="threshold1value",
            new_name="threshold1Value",
        ),
        migrations.RenameField(
            model_name="publicationsintopjournalpercentiles",
            old_name="threshold25value",
            new_name="threshold25Value",
        ),
        migrations.RenameField(
            model_name="publicationsintopjournalpercentiles",
            old_name="threshold5value",
            new_name="threshold5Value",
        ),
    ]
