# Generated by Django 4.1.9 on 2023-06-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainApp",
            "0006_rename_threshold10value_outputsintopcitationpercentiles_threshold10value_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborationimpact",
            name="InstitutionalValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość calkowita kolaboracji",
                null=True,
                verbose_name="Wartość calkowita",
            ),
        ),
        migrations.AlterField(
            model_name="collaborationimpact",
            name="InternationalValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość miedzynarodowa kolaboracji",
                null=True,
                verbose_name="Wartość miedzynarodowa",
            ),
        ),
        migrations.AlterField(
            model_name="collaborationimpact",
            name="NationalValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość narodowa kolaboracji",
                null=True,
                verbose_name="Wartość narodowa",
            ),
        ),
        migrations.AlterField(
            model_name="collaborationimpact",
            name="SingleAuthorshipValue",
            field=models.FloatField(
                blank=True,
                help_text="Wartość pojedynczego autorstwa kolaboracji",
                null=True,
                verbose_name="Wartość pojedynczego autorstwa",
            ),
        ),
    ]
