# Generated by Django 4.2.1 on 2023-06-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_faculty'),
        ('mainApp', '0004_publicationscountperyear'),
        ('mainApp', '0007_more_abstract_models'),
    ]

    operations = [
    ]
